// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHbp9pv5I2G4TVYlLNXjmLN23239SWeDA',
    appId: '1:820924187413:android:93943f2590186ffed95f1c',
    messagingSenderId: '820924187413',
    projectId: 'f-base-prod',
    storageBucket: 'f-base-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8KuQNqqiiTVLsMDzW4ADYSxKVZdKUUec',
    appId: '1:820924187413:ios:e8eb89dbe4ce94dcd95f1c',
    messagingSenderId: '820924187413',
    projectId: 'f-base-prod',
    storageBucket: 'f-base-prod.firebasestorage.app',
    androidClientId: '820924187413-c71b02i6akssa3h0lhlsggsof33ip43t.apps.googleusercontent.com',
    iosClientId: '820924187413-sjda87bhs6p1bel8acmpcp0qdcs27hg5.apps.googleusercontent.com',
    iosBundleId: 'com.fox.base.flutter',
  );
}
