// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DNu8rjg4_n70gRmozNIZRA0z_8AUfwY',
    appId: '1:320355629095:android:6becdda8c181ccff7cf602',
    messagingSenderId: '320355629095',
    projectId: 'f-base-dev',
    storageBucket: 'f-base-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLelccfWsC7ru2mYqy_qYy7IyHXFp6_w',
    appId: '1:320355629095:ios:bf5e9026a36b2fd97cf602',
    messagingSenderId: '320355629095',
    projectId: 'f-base-dev',
    storageBucket: 'f-base-dev.firebasestorage.app',
    androidClientId: '320355629095-6lmpf7or1gjpbsqjnodkrace7ar195to.apps.googleusercontent.com',
    iosClientId: '320355629095-4of9ccql8tl06h6g2b0sl0v7vh7663fc.apps.googleusercontent.com',
    iosBundleId: 'com.fox.base.flutter.dev',
  );
}
