package com.fox.base.flutter.bridge

import android.content.Context
import android.os.BatteryManager
import com.fox.base.flutter.generated.BatteryApi

/**
 * Android implementation of [BatteryApi] (generated by Pigeon).
 *
 * Registered in `MainActivity.kt`:
 * ```kotlin
 * BatteryApi.setUp(messenger, BatteryApiBridge(applicationContext))
 * ```
 *
 * @param context Application context used to access [BatteryManager].
 */
class BatteryApiBridge(private val context: Context) : BatteryApi {

    /**
     * Returns the current battery charge level as a percentage (0–100).
     *
     * Uses [BatteryManager.BATTERY_PROPERTY_CAPACITY] which returns -1 on
     * some emulators; callers should handle that edge case on the Dart side.
     */
    override fun getBatteryLevel(): Long {
        val bm = context.getSystemService(Context.BATTERY_SERVICE) as BatteryManager
        return bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY).toLong()
    }
}