package com.fox.base.flutter.bridge

import android.os.Build
import com.fox.base.flutter.generated.DeviceApi

/**
 * Android implementation of [DeviceApi] (generated by Pigeon).
 *
 * Registered in `MainActivity.kt`:
 * ```kotlin
 * DeviceApi.setUp(messenger, DeviceApiBridge())
 * ```
 */
class DeviceApiBridge : DeviceApi {

    /**
     * Returns [Build.ID] — a changelist number or label (e.g. `"QP1A.190711.020"`).
     *
     * Note: this is a build fingerprint, not a stable unique device ID.
     * For a persistent unique ID consider `Settings.Secure.ANDROID_ID` instead.
     */
    override fun getDeviceId(): String {
        return Build.ID
    }

    /**
     * Returns a human-readable device model string in the format
     * `"<Manufacturer> <Model>"` (e.g. `"Samsung SM-S921B"`).
     */
    override fun getModel(): String {
        return "${Build.MANUFACTURER} ${Build.MODEL}"
    }
}